### ISSUE TITLE
Post request returns undefined with json object

### ISSUE THREAD

**Issue by sanjaybaskaran01** [theProgrammerDavid/PostBaby#5]
Ref:
![image](https://user-images.githubusercontent.com/72266283/125694805-9da2e3bb-1c1b-48b4-90f4-bb5817459211.png)
Ref on postman:
![image](https://user-images.githubusercontent.com/72266283/125694913-98e0a1cc-48c1-4bd3-98c7-4abc7c0cd82b.png)

**Comment by theProgrammerDavid** [comment]
Fixed in 4d016fd
