### ISSUE TITLE
[BUG] [Windows] Initial Boot window size issue

### ISSUE THREAD

**Issue by DarthBenro008** [theProgrammerDavid/PostBaby#6]
**OS:** Windows 10
**Version:** Postbaby v0.0.1

**Description:**

The windows are too small and provide a bad user experience.

**Current Output:**

The windows look too small on the first boot

![image](https://user-images.githubusercontent.com/31009634/126676547-0646f0de-a743-417d-a430-3f035a401412.png)

**Expected Output:**

Nice and organised windows at first boot

**Comment by theProgrammerDavid** [comment]
Fixed in d2fb2a5
